#!/bin/sh

KUBECTL_SUDO_PROMPT=${KUBECTL_SUDO_PROMPT:-false}
if [ "$KUBECTL_SUDO_PROMPT" = true ]; then
    read -p "WARNING: Currently in context $(kubectl config current-context). Continue? (y/N) " yn
    case $yn in
        [Yy]* ) ;;
        * ) exit 1;;
    esac
fi

NEW_ARGS=""
PLUGIN_NAME=""
COMMAND=""

for arg in "$@"
do
    if [ ${arg} != "--"* ] && [ -z "${COMMAND}" ]; then
        COMMAND=${arg}
    fi
    plugin_path=$(which "kubectl-${COMMAND}" 2>/dev/null)
    if [ -x "${plugin_path}" ] && [ -z "${PLUGIN_NAME}" ]; then
        PLUGIN_NAME=$arg
        continue
    fi
    NEW_ARGS="${NEW_ARGS} ${arg}"
done

if [ -z "${PLUGIN_NAME}" ]; then
    exec kubectl --as=${USER} --as-group=system:masters "$@"
else
    exec kubectl ${PLUGIN_NAME} --as=${USER} --as-group=system:masters ${NEW_ARGS}
fi
